### PR TITLE
Update voicerom to real dumped voices

### PR DESCRIPTION
**Pull request by MP2E**
based on Kitrinx's commit in SMS-MiSTer

### CODE REVIEW

**Comment by Kitrinx** [comment]
Please add the VRC7 instruments with an ifdef in the code to prevent accidental use of the wrong instruments. This is what I was doing before you decided to be first.

**Comment by sorgelig** [comment]
> Please add the VRC7 instruments with an ifdef in the code to prevent accidental use of the wrong instruments. This is what I was doing before you decided to be first.

i've no idea what's that.

**Comment by MP2E** [comment]
I was just trying to help, not be first. I saw an open PR and figured it was finished. My mistake

**Comment by MP2E** [comment]
I think I'll just leave it to someone else :/

**Pull request closed without merging**
